### ISSUE TITLE
How To Get Index on onChange Handler?

### ISSUE THREAD

**Issue by kapilpipaliya** [thisbeyond/solid-select#25]
Thank you so much for the great library.
I am using a single select and I want to get an index when option is selected.
how to get an index of the function on `onChange` Handler?

**Comment by martinpengellyphillips** [comment]
That's not supported currently. It would be complex to implement as well because the selected value is independent of the options (you can actually set a value not present in the options programatically for example). 

Instead you need to track it separately yourself (or use a unique id for each option as an object).
